FROM python:3.11-slim

WORKDIR /app

# Настраиваем системную таймзону внутри Linux
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "HSE-go-AI-API.py"]